#!/usr/bin/env python3
"""Regenerate data/archetype-art.js from YGOPRODeck.

Metaslice looks an archetype up live when you ask for art. This index is what
it falls back to when that lookup cannot be reached, so Get all art still has
somewhere to get a portrait from. It holds one image URL per archetype and
nothing else — some 50-odd KB against the 20 MB the full card dump weighs.

    python3 tools/build-archetype-index.py

Re-run it when new archetypes have been printed; the file it writes is meant
to be committed. Nothing else in the repository needs building.
"""

import datetime
import json
import pathlib
import sys
import urllib.error
import urllib.request

DUMP = "https://db.ygoprodeck.com/api/v7/cardinfo.php"
# The default urllib agent is refused with a 403.
UA = {"User-Agent": "metaslice-archetype-index (+https://metaslice.reizu.dev)"}
OUT = pathlib.Path(__file__).resolve().parent.parent / "data" / "archetype-art.js"


def fetch(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=120) as r:
        return json.load(r)


def build(cards):
    """First card of each archetype, in the order the dump lists them.

    That is the same one `?archetype=X&num=1&offset=0` returns, so a portrait
    from this index matches what the live lookup would have given you.
    """
    art = {}
    for card in cards:
        name = card.get("archetype")
        if not name or name in art:
            continue
        images = card.get("card_images") or [{}]
        url = images[0].get("image_url_cropped") or images[0].get("image_url_small")
        if url:
            art[name] = url
    return art


def main():
    try:
        cards = fetch(DUMP)["data"]
    except (urllib.error.URLError, KeyError, ValueError) as err:
        sys.exit(f"Could not read the card dump: {err}")

    art = build(cards)
    if len(art) < 500:
        sys.exit(f"Only {len(art)} archetypes found — that looks wrong, refusing to write.")

    # One archetype per line, sorted. Costs a few KB over a minified object and
    # makes the file readable and greppable — and, more to the point, makes a
    # refresh show up as a handful of added lines rather than the whole file
    # arriving as one rewritten line nobody can review.
    body = json.dumps(art, ensure_ascii=False, sort_keys=True, indent=2)
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        "// Generated by tools/build-archetype-index.py — do not edit by hand.\n"
        "// One portrait URL per archetype, used only when the live YGOPRODeck\n"
        "// lookup cannot be reached.\n"
        "//\n"
        "// The object below is plain JSON. It is wrapped in an assignment rather\n"
        "// than shipped as .json so a script tag can load it, which resolves from\n"
        "// file:// — fetch of a sibling file does not. To pull the JSON back out:\n"
        "//     sed '1,/^window.ARCHETYPE_ART = /d;$d' data/archetype-art.js\n"
        f'window.ARCHETYPE_ART_GENERATED = "{datetime.date.today().isoformat()}";\n'
        f"window.ARCHETYPE_ART = {body};\n",
        encoding="utf-8",
    )
    print(f"{len(art)} archetypes from {len(cards)} cards -> {OUT.relative_to(OUT.parent.parent)} "
          f"({OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
